version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: knowledge-hub-api
    restart: always
    ports:
      - "8080:${HTTP_PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - HTTP_PORT=${HTTP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - PG_POOL_MAX=${PG_POOL_MAX}
      - PG_URL=${PG_URL}
      - METRICS_ENABLED=${METRICS_ENABLED}
      - SWAGGER_ENABLED=${METRICS_ENABLED}
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: knowledge-hub-postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: