version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/knowledge-hub:latest
    container_name: knowledge-hub-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=knowledge-hub
      - APP_VERSION=1.0.0
      - HTTP_PORT=8080
      - LOG_LEVEL=info
      - PG_POOL_MAX=10
      - PG_URL=postgres://postgres:postgres@postgres:5432/knowledge_hub
      - METRICS_ENABLED=true
      - SWAGGER_ENABLED=true
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: knowledge-hub-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowledge_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: